"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DieReason = void 0;
var DieReason;
(function (DieReason) {
    DieReason[DieReason["NO_REASON"] = 0] = "NO_REASON";
    DieReason[DieReason["FEED_DIE"] = 1] = "FEED_DIE";
    DieReason[DieReason["FROZE_DIE"] = 2] = "FROZE_DIE";
    DieReason[DieReason["PLAYER_KILLED"] = 3] = "PLAYER_KILLED";
    DieReason[DieReason["FIRE_CLOSE_DAMAGE"] = 4] = "FIRE_CLOSE_DAMAGE";
    DieReason[DieReason["SPIDER_KILLED"] = 5] = "SPIDER_KILLED";
    DieReason[DieReason["WOLF_KILLED"] = 6] = "WOLF_KILLED";
    DieReason[DieReason["FOX_KILLED"] = 7] = "FOX_KILLED";
    DieReason[DieReason["BEAR_KILLED"] = 8] = "BEAR_KILLED";
    DieReason[DieReason["DRAGON_KILED"] = 9] = "DRAGON_KILED";
    DieReason[DieReason["SPIKE_KILLED"] = 10] = "SPIKE_KILLED";
    DieReason[DieReason["GHOST_DIE"] = 11] = "GHOST_DIE";
    DieReason[DieReason["RAW_FOOD_KILLED"] = 12] = "RAW_FOOD_KILLED";
    DieReason[DieReason["WATER_DIED"] = 13] = "WATER_DIED";
    DieReason[DieReason["OXYGEN_DIED"] = 14] = "OXYGEN_DIED";
    DieReason[DieReason["PIRAHN_DIE"] = 15] = "PIRAHN_DIE";
    DieReason[DieReason["KRAKEN_DIE"] = 16] = "KRAKEN_DIE";
    DieReason[DieReason["VAMPIRE_SUN_DIE"] = 17] = "VAMPIRE_SUN_DIE";
    DieReason[DieReason["VAMPIRE_GARLIC_1"] = 18] = "VAMPIRE_GARLIC_1";
    DieReason[DieReason["VAMPIRE_GARLIC_2"] = 19] = "VAMPIRE_GARLIC_2";
    DieReason[DieReason["THORN_DIE"] = 20] = "THORN_DIE";
})(DieReason || (exports.DieReason = DieReason = {}));
